#include "combat/CardInstance.h"
#include "game/Card.h"
#include "constants/SaveFileMappings.h"
#include <fstream>
using namespace sts;
using json=nlohmann::json;
int main(int argc,char**argv){
 json rows;std::ifstream(argv[1])>>rows;int failures=0;
 for(auto row:rows){
  const auto id=row.at("id").get<CardId>();if(id==CardId::INVALID)throw std::runtime_error("unknown original card");
  Card deck(id);CardInstance combat(id);
  for(int i=0;i<row["requested_upgrades"].get<int>();i++){deck.upgrade();combat.upgrade();}
  // Burn+ is generated by Hexaghost; it is not eligible for player upgrades.
  if(id==CardId::BURN)combat=CardInstance(id,row["upgrades"].get<int>()>0);
  json actual={{"cost",combat.cost},{"ethereal",combat.isEthereal()},{"exhaust",combat.doesExhaust()},{"innate",deck.isInnate()},{"target",combat.requiresTarget()},{"strike",combat.isStrikeCard()},{"can_upgrade",combat.canUpgrade()},{"upgrades",combat.getUpgradeCount()}};
  if(row.contains("base_damage")){actual["base_damage"]=deck.getBaseDamage();actual["type"]=cardTypeStrings[static_cast<int>(deck.getType())];actual["rarity"]=cardRarityStrings[static_cast<int>(deck.getRarity())];actual["color"]=cardColorStrings[static_cast<int>(getCardColor(id))];}
  json differences=json::object();for(auto it=actual.begin();it!=actual.end();++it)if(it.value()!=row.at(it.key()))differences[it.key()]={{"original",row.at(it.key())},{"simulator",it.value()}};
  // Direct construction of an upgraded card must match upgrading a base card.
  if(id!=CardId::SEARING_BLOW){CardInstance direct(id,row["upgrades"].get<int>()>0);if(direct.cost!=combat.cost)differences["direct_cost"]={{"original",row["cost"]},{"simulator",direct.cost}};}
  if(!differences.empty()){++failures;std::cout<<row["id"]<<" +"<<row["requested_upgrades"]<<" "<<differences.dump()<<'\n';}
 }
 std::cout<<rows.size()-failures<<"/"<<rows.size()<<" original card metadata rows passed\n";return failures?1:0;
}
