#include "game/GameContext.h"
#include "game/SaveFile.h"
#include "game/Game.h"
#include "combat/BattleContext.h"
#include "combat/Actions.h"
#include "sim/search/GameAction.h"
#include "sim/search/BattleScumSearcher2.h"
#include "sim/search/ScumSearchAgent2.h"
#include <fstream>
#include <stdexcept>
#include <cstdio>
using namespace sts;
void check(bool value,const char*message){if(!value)throw std::runtime_error(message);}
SaveFile fixture(){SaveFile s{};s.seed=123;s.cc=CharacterClass::IRONCLAD;s.ascension_level=20;s.act_num=1;s.floor_num=1;s.room_x=0;s.room_y=0;s.current_room=Save::RoomType::MONSTER_ROOM;s.current_health=60;s.max_health=80;s.gold=99;s.purgeCost=125;s.boss_list={MonsterEncounter::HEXAGHOST,MonsterEncounter::SLIME_BOSS,MonsterEncounter::THE_GUARDIAN};s.monster_list={MonsterEncounter::CULTIST,MonsterEncounter::JAW_WORM};s.elite_monster_list={MonsterEncounter::GREMLIN_NOB};s.cards={Card(CardId::STRIKE_RED),Card(CardId::DEFEND_RED),Card(CardId::ASCENDERS_BANE)};s.relics={RelicId::BURNING_BLOOD};s.relic_counters={-1};s.potions={Potion::EMPTY_POTION_SLOT,Potion::EMPTY_POTION_SLOT};s.common_relics={RelicId::ANCHOR};s.event_list={Event::BIG_FISH};s.one_time_event_list={Event::DUPLICATOR};return s;}
int main(int argc,char**argv){try{std::string mode=argv[1];
 if(mode=="save_replace"){auto s=fixture();GameContext g(CharacterClass::IRONCLAD,456,20);g.redKey=g.greenKey=g.blueKey=true;g.obtainRelic(RelicId::OLD_COIN);g.initFromSave(s);g.initFromSave(s);check(g.deck.size()==3,"loading duplicated the master deck");check(g.relics.size()==1,"loading retained old relics");check(!g.redKey&&!g.greenKey&&!g.blueKey,"loading retained old keys");check(g.commonRelicPool.size()==1&&g.eventList.size()==1&&g.specialOneTimeEventList.size()==1,"loading accumulated run pools");check(g.shopRemoveCount==2,"purge price history lost");check(g.info.encounter==MonsterEncounter::CULTIST&&g.monsterListOffset==1,"loading skipped the saved encounter");}
 else if(mode=="save_bottle"){auto s=fixture();s.cards={Card(CardId::BASH),Card(CardId::BASH,1),Card(CardId::RITUAL_DAGGER),Card(CardId::RITUAL_DAGGER)};s.cards[2].misc=19;s.cards[3].misc=37;s.bottledCards[0]=CardId::BASH;s.bottledUpgrades[0]=1;Deck d;d.initFromSaveFile(s);check(d.bottleIdxs[0]==1,"bottled upgrade identity lost");s.bottledCards[0]=CardId::RITUAL_DAGGER;s.bottledUpgrades[0]=0;s.bottledMisc[0]=37;d.initFromSaveFile(s);check(d.size()==4&&d.bottleIdxs[0]==3,"bottled misc identity lost");}
 else if(mode=="save_encoding"){const std::string source=argv[2],out=source+".save";{std::ofstream f(source);f<<"{\"seed\":123,\"gold\":99}";}check(SaveFile::getJsonFromSaveFile(source)=="{\"seed\":123,\"gold\":99}","plain original save rejected");std::ifstream in(source);SaveFile::writeJsonToSaveFile(in,out);check(SaveFile::getJsonFromSaveFile(out)=="{\"gold\":99,\"seed\":123}","save obfuscation is not reversible");std::remove(source.c_str());std::remove(out.c_str());}
 else if(mode=="save_act4"){auto s=fixture();s.act_num=4;s.floor_num=53;s.room_x=3;s.room_y=0;s.current_room=Save::RoomType::REST_ROOM;s.boss_list={MonsterEncounter::THE_HEART};s.relics.push_back(RelicId::ANCIENT_TEA_SET);s.relic_counters.push_back(-1);GameContext g;g.initFromSave(s);check(g.screenState==ScreenState::REST_ROOM&&g.curRoom==Room::REST,"Act 4 map not restored");check(g.relics.getRelicValue(RelicId::ANCIENT_TEA_SET)==-2,"load skipped room entry hook");search::GameAction(2).execute(g);check(g.redKey&&g.screenState==ScreenState::MAP_SCREEN,"loaded rest room cannot continue");}
 else if(mode=="save_postcombat"){auto s=fixture();s.post_combat=true;s.relics.push_back(RelicId::MAW_BANK);s.relic_counters.push_back(-1);Save::CombatReward gold{};gold.type=Save::CombatRewardType::GOLD;gold.amount=17;s.combat_rewards={gold};GameContext g;g.initFromSave(s);check(g.screenState==ScreenState::REWARDS&&g.curHp==60&&g.gold==99,"post-combat reload reran fight or room hooks");check(g.monsterListOffset==0,"post-combat reload consumed next encounter");check(g.info.rewardsContainer.gold[0]==17&&g.info.rewardsContainer.cardRewardCount==1,"post-combat rewards missing");s.smoked=true;g.initFromSave(s);check(g.info.rewardsContainer.getTotalCount()==0,"smoke escape regained rewards after reload");}
 else if(mode=="save_event_rng"){auto s=fixture();s.current_room=Save::RoomType::EVENT_ROOM;s.post_combat=true;s.completedEvent=Event::DEAD_ADVENTURER;GameContext g;g.initFromSave(s);Random expected(s.seed+s.floor_num);expected.randomLong();expected.random(2);check(g.miscRng.seed0==expected.seed0&&g.miscRng.seed1==expected.seed1&&g.miscRng.counter==2,"completed event reload lost constructor RNG");check(g.screenState==ScreenState::REWARDS,"completed event reopened instead of rewards");}
 else if(mode=="tea_once"){GameContext g(CharacterClass::IRONCLAD,123,20);g.obtainRelic(RelicId::ANCIENT_TEA_SET);g.relicsOnEnterRoom(Room::REST);g.relicsOnEnterRoom(Room::SHOP);g.regainControlAction=[](GameContext&a){a.screenState=ScreenState::MAP_SCREEN;};BattleContext b;b.init(g,MonsterEncounter::CULTIST);check(b.player.energy==5,"tea lost across shop");b.outcome=Outcome::PLAYER_ESCAPE;b.exitBattle(g);check(g.relics.getRelicValue(RelicId::ANCIENT_TEA_SET)==-1,"tea not consumed");BattleContext next;next.init(g,MonsterEncounter::CULTIST);check(next.player.energy==3,"tea applied a second time");}
 else if(mode=="reward_sampling"){bool chosen[3]={false,false,false};for(int seed=1;seed<=128;seed++){GameContext g(CharacterClass::IRONCLAD,123,20);g.regainControlAction=[](GameContext&a){a.screenState=ScreenState::MAP_SCREEN;};CardReward offer;offer.push_back(Card(CardId::INFLAME));offer.push_back(Card(CardId::ANGER));offer.push_back(Card(CardId::DEMON_FORM));g.openCombatRewardScreen(Rewards(offer));search::ScumSearchAgent2 agent;agent.rng.seed(seed);int size=g.deck.size();agent.weightedCardRewardPolicy(g);if(g.deck.size()>size){auto id=g.deck.cards.back().id;chosen[id==CardId::INFLAME?0:(id==CardId::ANGER?1:2)]=true;}}check(chosen[0]&&chosen[1]&&chosen[2],"weighted reward sampling always chose the last candidate");}
 else if(mode=="bottled_identity"){for(int seed=0;seed<16;seed++){GameContext g(CharacterClass::IRONCLAD,123,20);g.deck=Deck();g.deck.obtainRaw(Card(CardId::ANGER));g.deck.obtainRaw(Card(CardId::ANGER));g.deck.bottleCard(1,CardType::ATTACK);g.miscRng=Random(seed);Random expected(seed);std::vector<int> idxs{0,1};java::Collections::shuffle(idxs.begin(),idxs.end(),java::Random(expected.randomLong()));int selected=g.getRandomPlayerNonBasicCardIdx();check(selected==idxs[0],"random selection replaced exact bottled card with equal card face");g.deck.remove(g,selected);check(g.deck.isCardBottled(0)==(selected==0),"removal kept the wrong bottled identity");}}
 else if(mode=="large_selection"){GameContext g(CharacterClass::IRONCLAD,123,20);g.deck=Deck();g.deck.obtain(g,Card(CardId::ANGER),299);g.deck.obtain(g,Card(CardId::BASH));g.regainControlAction=[](GameContext&a){a.screenState=ScreenState::MAP_SCREEN;};g.obtainRelic(RelicId::DOLLYS_MIRROR);search::GameAction selected(299);check(selected.getIdx1()==299&&search::GameAction(selected.bits).getIdx1()==299,"serialized selection index wrapped at 256");selected.execute(g);check(g.deck.size()==301&&g.deck.cards.back().id==CardId::BASH,"large deck selected a different card");check(search::GameAction(7,3).bits==0x307,"legacy action encoding changed");}
 else if(mode=="artifact_entry"){for(bool reverse:{false,true}){GameContext g(CharacterClass::IRONCLAD,123,20);g.obtainRelic(reverse?RelicId::GREMLIN_VISAGE:RelicId::CLOCKWORK_SOUVENIR);g.obtainRelic(reverse?RelicId::CLOCKWORK_SOUVENIR:RelicId::GREMLIN_VISAGE);BattleContext b;b.init(g,MonsterEncounter::CULTIST);check(b.player.getStatus<PlayerStatus::WEAK>()==0&&b.player.getStatus<PlayerStatus::ARTIFACT>()==0,"Artifact did not block entry Weak in both relic orders");}}
 else if(mode=="large_deck"){GameContext g(CharacterClass::IRONCLAD,123,20);g.deck=Deck();g.deck.obtain(g,Card(CardId::ANGER),128);g.regainControlAction=[](GameContext&a){a.screenState=ScreenState::MAP_SCREEN;};check(g.deck.size()==128&&g.deck.cardTypeCounts[0]==128,"large deck corrupted card storage or counts");for(auto c:g.deck.cards)check(c.id==CardId::ANGER,"large deck changed card identity");g.obtainRelic(RelicId::EMPTY_CAGE);check(g.info.toSelectCards.size()==128,"large removal candidates truncated");search::GameAction(127).execute(g);search::GameAction(126).execute(g);check(g.deck.size()==126,"large removal lost selected cards");BattleContext b;b.init(g,MonsterEncounter::AUTOMATON);check(b.cards.drawPile.size()+b.cards.cardsInHand==126,"large battle deck not retained");b.addToBot(Actions::ViolenceAction(3));b.inputState=InputState::EXECUTING_ACTIONS;b.executeActions();check(b.cards.cardsInHand==8,"Violence failed with more than 64 attacks");b.monsters.arr[0].initSpawnedMonster(b,MonsterId::BRONZE_ORB,0,55);b.monsters.arr[0].stasisAction(b);check(b.cards.stasisCards[0].getId()==CardId::ANGER,"Stasis failed with more than 64 matching cards");}
 else if(mode=="dead_complete"){GameContext g(CharacterClass::IRONCLAD,123,20);g.floorNum=8;g.curEvent=Event::DEAD_ADVENTURER;g.curRoom=Room::EVENT;g.miscRng=Random(19);g.regainControlAction=[](GameContext&a){a.screenState=ScreenState::MAP_SCREEN;};g.setupEvent();for(int i=0;i<3;i++)search::GameAction(0).execute(g);check(g.info.phase==3&&g.screenState==ScreenState::MAP_SCREEN,"three rewards still allow another search");}
 else if(mode=="search_stalemate"){GameContext g(CharacterClass::IRONCLAD,280,20);BattleContext b;b.init(g,MonsterEncounter::CULTIST);b.turn=500;auto hp=b.player.curHp;search::BattleScumSearcher2 searcher(b);searcher.search(10);check(searcher.outcomePlayerHp==-1&&searcher.bestActionSequence.empty(),"truncated branch presented as a completed winning solution");check(b.outcome==Outcome::UNDECIDED&&b.player.curHp==hp,"search cutoff changed actual combat outcome");}
  else if(mode=="battle_reinit"){GameContext g(CharacterClass::IRONCLAD,132,20);BattleContext b;b.player.cc=CharacterClass::DEFECT;b.init(g,MonsterEncounter::CULTIST);check(b.player.cc==CharacterClass::IRONCLAD,"combat lost the run character");b.player.buff<PlayerStatus::STRENGTH>(99);b.player.energy=77;b.init(g,MonsterEncounter::CULTIST);check(b.player.energy==3&&b.player.getStatus<PlayerStatus::STRENGTH>()==0,"reused battle retained previous player state");}
  else if(mode=="agent_simulation_total"){GameContext g(CharacterClass::IRONCLAD,123,20);search::ScumSearchAgent2 agent;check(agent.simulationCountTotal==0,"default-constructed agent read an uninitialized simulation total");agent.simulationCountBase=1000;BattleContext b;b.init(g,MonsterEncounter::CULTIST);agent.playoutBattle(b);check(agent.simulationCountTotal>0,"direct playoutBattle entry never accumulated the simulation total");}
 else if(mode=="repto_capacity"){GameContext g(CharacterClass::IRONCLAD,123,20);BattleContext b;b.init(g,MonsterEncounter::REPTOMANCER);auto&r=b.monsters.arr[2];r.reptomancerSummon(b,2);check(b.monsters.monstersAlive==5,"initial daggers not summoned");b.monsters.arr[4].curHp=0;--b.monsters.monstersAlive;r.reptomancerSummon(b,2);check(b.monsters.monstersAlive==5&&b.monsters.arr[4].curHp>0,"one available slot did not produce one dagger");r.reptomancerSummon(b,2);check(b.monsters.monstersAlive==5,"full board spawned extra dagger");}
 else throw std::runtime_error("unknown case");
 std::cout<<mode<<" passed\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
